### ISSUE TITLE
Problema com versão do Mac no SMBios e kext de internet.

### ISSUE THREAD

**Issue by rodriggesacademico** [luchina-gabriel/BASE-EFI-INTEL-DESKTOP-9THGEN-COFFEE-LAKE-REFRESH#1]
Comigo só funcionou utilizando a versão iMacPro1,1. Pesquisei em alguns fórus e vi que o i3 9100F só funcionaria nessa versão, pois é uma versão sem placa de vídeo integrada.

Sobre a internet vi que minha placa mãe utiliza um codec mais antigo, oq me limita a 100Mbps. Acabei utilizando a kext RealtekRTL8100.kext disponibilizada em: https://www.insanelymac.com/forum/files/file/259-realtekrtl8100-binary/

SETUP
Processador: i3 9100f
Placa de Vídeo: rx570 8gb
Memória: 16gb
Placa Mãe: Jginyue b250

**Comment by luchina-gabriel** [comment]
Funcionou com a iMacPro1,1 por conta do seu processador que não tem vídeo integrado, também pode usar MacPro7,1 como SMBIOS caso queira.

Valeu pelo feedback.
